stages:
  - test

variables:
  SECRET_KEY: $SECRET_KEY

test_job:
  stage: test
  image: python:3.x
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pytest app
    - pylint app
    - mypy app
    - coverage run -m pytest app
    - coverage report -m
